#
# Copyright (c) 2022 Intel Corporation. 
#
# SPDX-License-Identifier: Apache-2.0
#
#
nodes:
  - address: {{ .Kitconfig.Parameters.GlobalSettings.ProviderIP }}
    user: {{ .User }}
    role:
      - controlplane
      - etcd
      - worker
    ssh_key_path: ~/.ssh/id_rsa
ssh_key_path: ~/.ssh/id_rsa
private_registries:
    - url: {{ .Kitconfig.Parameters.GlobalSettings.ProviderIP }}:{{ .Kitconfig.Parameters.GlobalSettings.RegistryPort }}/docker.io
      user: {{ .Kitconfig.Parameters.Customconfig.Registry.User }}
      password: {{ .Kitconfig.Parameters.Customconfig.Registry.Password }}
      is_default: true
system_images:
ingress:
{{- range .Extensions -}}
{{- if eq .Name "ingress" -}}
{{- range .Extension.Extension -}}
{{- if eq .Name "rke-ingress" -}}
{{- range .Config -}}
{{- if eq .Name "provider"}}
  provider: {{ .Value }}
{{- end -}}
{{- if eq .Name "default-backend"}}
  default_backend: {{ .Value }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end }}