#
# Copyright (c) 2022 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#
cluster_providers:
- name: kind
  version: "v0.14.0"
  images:
  - name: img_node
    repo_tag: "kindest/node:v1.24.2"
  - name: img_haproxy
    repo_tag: "docker.io/kindest/base:v20220518-0ffcf8d6"
  binaries:
  - name: kindtool
    url: "https://kind.sigs.k8s.io/dl/v0.14.0/kind-linux-amd64"
    sha256: "af5e8331f2165feab52ec2ae07c427c7b66f4ad044d09f253004a20252524c8b"

- name: rke
  version: "1.3.12"
  binaries:
  - name: rketool
    url: "https://github.com/rancher/rke/releases/download/v1.3.12/rke_linux-amd64"
    sha256: "579da2206aec09cadccd8d6f4818861e78a256b6ae550a229335e500a472bd50"

capi_cluster_providers:
- name: metal3
  runtime: "containerd"
  providers:
  - provider_type: "CoreProvider"
    name: "cluster-api"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/core-components.yaml"
    parameters:
      provider_label: "cluster-api"
      version: "v1.2.0"
      metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/metadata.yaml"
  - provider_type: "BootstrapProvider"
    name: "kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/bootstrap-components.yaml"
    parameters:
      provider_label: "bootstrap-kubeadm"
      version: "v1.2.0"
      metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/metadata.yaml"
  - provider_type: "ControlPlaneProvider"
    name: "kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/control-plane-components.yaml"
    parameters:
      provider_label: "control-plane-kubeadm"
      version: "v1.2.0"
      metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/metadata.yaml"
  - provider_type: "InfrastructureProvider"
    name: "metal3"
    url: "https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.1.2/infrastructure-components.yaml"
    parameters:
      provider_label: "infrastructure-metal3"
      version: "v1.1.1"
      metadata: "https://github.com/metal3-io/cluster-api-provider-metal3/releases/download/v1.1.1/metadata.yaml"
  cert-manager:
    version: "v1.9.0"
    url: "https://github.com/jetstack/cert-manager/releases/download/v1.9.0/cert-manager.yaml"
  binaries:
  - name: clusterctl
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.1.3/clusterctl-linux-amd64"
  - name: kubectl
    url: "https://dl.k8s.io/v1.23.4/bin/linux/amd64/kubectl"
  - name: kubeadm
    url: "https://dl.k8s.io/v1.23.4/bin/linux/amd64/kubadm"
  - name: kubelet
    url: "https://dl.k8s.io/v1.23.4/bin/linux/amd64/kubelet"
  - name: "crio"
    url: "https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.2cf9dbf1a447d25931008c1815de407d9e5749f7.tar.gz"
    version: "v1.23.3"
    revision: "cri-o.amd64.2cf9dbf1a447d25931008c1815de407d9e5749f7.tar.gz"
  - name: "containerd"
    url: "https://github.com/containerd/containerd/releases/download/v1.6.6/cri-containerd-cni-1.6.6-linux-amd64.tar.gz"
    version: "1.6.6"
  - name: "oras"
    version: "0.13.0"
    url: "https://github.com/oras-project/oras/releases/download/v0.13.0/oras_0.13.0_linux_amd64.tar.gz"
- name: byoh
  runtime: "containerd"
  providers:
  - provider_type: "CoreProvider"
    name: "cluster-api"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/core-components.yaml"
    parameters:
      provider_label: "cluster-api"
      version: "v1.2.0"
      metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/metadata.yaml"
  - provider_type: "BootstrapProvider"
    name: "kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/bootstrap-components.yaml"
    parameters:
      provider_label: "bootstrap-kubeadm"
      version: "v1.2.0"
      metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/metadata.yaml"
  - provider_type: "ControlPlaneProvider"
    name: "kubeadm"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/control-plane-components.yaml"
    parameters:
      provider_label: "control-plane-kubeadm"
      version: "v1.2.0"
      metadata: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/metadata.yaml"
  - provider_type: "InfrastructureProvider"
    name: "byoh"
    url: "https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/releases/download/v0.2.0/infrastructure-components.yaml"
    parameters:
      provider_label: "infrastructure-byoh"
      version: "v0.2.0"
      metadata: file://{{ .Workspace }}/config/cluster-provider/capi/byoh/metadata.yaml
  cert-manager:
    version: "v1.9.0"
    url: "https://github.com/jetstack/cert-manager/releases/download/v1.9.0/cert-manager.yaml"
  images:
  - "ghcr.io/kube-vip/kube-vip:v0.3.5"
  - "k8s.gcr.io/coredns/coredns:v1.8.6"
  - "k8s.gcr.io/etcd:3.5.1-0"
  - "k8s.gcr.io/kube-apiserver:v1.23.5"
  - "k8s.gcr.io/kube-controller-manager:v1.23.5"
  - "k8s.gcr.io/kube-proxy:v1.23.5"
  - "k8s.gcr.io/kube-scheduler:v1.23.5"
  - "k8s.gcr.io/pause:3.6"
  - "projects.registry.vmware.com/cluster_api_provider_bringyourownhost/cluster-api-byoh-controller:v0.2.0"
  - "gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0"
  - "k8s.gcr.io/cluster-api/cluster-api-controller:v1.2.0"
  - "k8s.gcr.io/cluster-api/kubeadm-bootstrap-controller:v1.2.0"
  - "k8s.gcr.io/cluster-api/kubeadm-control-plane-controller:v1.2.0"
  - "quay.io/jetstack/cert-manager-cainjector:v1.9.0"
  - "quay.io/jetstack/cert-manager-controller:v1.9.0"
  - "quay.io/jetstack/cert-manager-webhook:v1.9.0"
  binaries:
  - name: clusterctl
    revision: "clusterctl-linux-amd64"
    url: "https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/clusterctl-linux-amd64" 
  - name: cri-tools
    revision: "crictl-v1.24.2-linux-amd64.tar.gz"
    url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.24.2/crictl-v1.24.2-linux-amd64.tar.gz"
    sha256: "53432dd365f7bf045c1e65ee2e44c74df6a0a8f0a798f640a945c8e07ad8682e"
  - name: kubectl
    url: "https://dl.k8s.io/v1.23.5/bin/linux/amd64/kubectl"
  - name: kubeadm
    url: "https://dl.k8s.io/v1.23.5/bin/linux/amd64/kubeadm"
  - name: kubelet
    url: "https://dl.k8s.io/v1.23.5/bin/linux/amd64/kubelet"
  - name: "crio"
    version: "v1.23.3"
    revision: "cri-o.amd64.2cf9dbf1a447d25931008c1815de407d9e5749f7.tar.gz"
    url: "https://storage.googleapis.com/cri-o/artifacts/cri-o.amd64.2cf9dbf1a447d25931008c1815de407d9e5749f7.tar.gz"
  - name: "containerd"
    version: "1.6.6"
    url: "https://github.com/containerd/containerd/releases/download/v1.6.6/cri-containerd-cni-1.6.6-linux-amd64.tar.gz"
    revision: "cri-containerd-cni-1.6.6-linux-amd64.tar.gz"
  - name: host-agent
    version: "v0.2.0"
    revision: "byoh-hostagent-linux-amd64"
    url: "https://github.com/vmware-tanzu/cluster-api-provider-bringyourownhost/releases/download/v0.2.0/byoh-hostagent-linux-amd64" 
  - name: "oras"
    version: "0.13.0"
    revision: "oras_0.13.0_linux_amd64.tar.gz"
    url: "https://github.com/oras-project/oras/releases/download/v0.13.0/oras_0.13.0_linux_amd64.tar.gz"
